version: "3"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - FLASK_ENV=development
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=true
    ports:
      - "5001:5000"